### ISSUE TITLE
Error DownloadToDb

### ISSUE THREAD

**Issue by jmimu** [DexcTrack/dexctrack#5]
On Linux Mint 19.3, with Python 2.7.17, python-sqlite 1.0.1-12, when using a G4, I got this error:

> DownloadToDb() : Rolling back SQL changes due to exception = You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

I added
`conn.text_factory = str`
on readReceiver.py at line 125, but I also had to convert full_trend from string to integer.

**Comment by jmimu** [comment]
With the latest master I just had to change full_trend return into:
`ord(self.data[3])`

**Comment by DexcTrack** [comment]
I've merged in a slightly different solution. In the G5/G6 version of EGVRecord, the full_trend data type is set to byte ('B') whereas the G4 version had the data type set to char ('c'). I've modified the G4 version to be consistent with the G5/G6 version. When the data type is properly set, there's no need to invoke ord().

**Comment by DexcTrack** [comment]
Your suggested change of adding
`conn.text_factory = str`
scares me a bit. I'm not sure why it's necessary, or what unintended consequences it might cause. I wonder if it worked around something which we have subsequently fixed with recent G4 related modifications. Could you try commenting out that line and see if it is still needed?

**Comment by jmimu** [comment]
Your solution is way better. I checked, it works well.
Thanks!
